### Spring properties

spring:

  # Service registers under this name
  application:
    name: user
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8089

  # DATA SOURCE
  datasource:
    url: jdbc:mysql://instanciadb.ciakhac9rhp8.us-east-1.rds.amazonaws.com:3306/users_lucaticket?useUnicode=yes&characterEncoding=UTF-8
    username: Administrator
    password: Administrator2
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 8092
  # Disable Spring Boot's "Whitelabel" default error page, so we can use our own
  error:
    whitelabel:
      enabled: false


# tatata

