### Spring properties

spring:

# Service registers under this name
  application:
    name: event
  config:
    import: 'optional:configserver:'
  cloud:
      config:
        uri: http://localhost:8089

# DATA SOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 8092
  # Disable Spring Boot's "Whitelabel" default error page, so we can use our own
  error:
    whitelabel:
      enabled: false


# tatata

